### PR TITLE
file upload: normalize filename

### PR DESCRIPTION
**Pull request by oemueller**
remove whitespace, äöüß ... etc. from filename.

When uploading images to Enduro we should make sure the filename is "normalized"

### CODE REVIEW

**Comment by Gottwik** [comment]
Great job! Happy to accept more pull requests.

**Comment by oemueller** [comment]
glad to help :-) I forgot one thing: shall we keep "-" dashes in filenames? I could extend the RegEx

**Comment by Gottwik** [comment]
you decide. I added you as collaborator so you can merge your pull request :-)

**Comment by oemueller** [comment]
ok, thanks

**Pull request merged**
