### PR TITLE
Suggession to fix bug #148

### PR DESCRIPTION
**Pull request by serbol**
https://github.com/Gottwik/Enduro/issues/148
Still need to implement reload

### CODE REVIEW

**Comment by serbol** [comment]
Please, check test details! Error is related to Stylus, but not to my JS code changes. I haven't done any changes in stylus tasks!

**Comment by CosmoMyzrailGorynych** [comment]
@serbol it's okay, Gottwik and I know about this upstream change.
But we are too busy @_@

**Comment by CosmoMyzrailGorynych** [comment]
`if (err) throw err;`

afaik this line will kill the entire enduro process if something goes wrong. This function should at least fs.stat the file to determine it exists and can be deleted. And there should be paths checks in order to avoid going upwards in a file tree with `/../` in request's data.

**Comment by serbol** [comment]
"And there should be paths checks in order to avoid going upwards in a file tree with /../ in request's data."
How it can be possible? Can you give any examples?
Please, check las commit.

**Comment by Gottwik** [comment]
Hey, good job @serbol . I never implemented page deletion since I was not sure how it will play with juicebox. I guess the way you implemented it, the page will be back after a juicebox pull. But anyway, it's nice at least for the non-juicebox users for the meantime 👍

**Pull request merged**
