### PR TITLE
chore(build): Updated build folder to use config

### PR DESCRIPTION
**Pull request by justindra**

### CODE REVIEW

**Comment by justindra** [comment]
@Gottwik will need your guidance on updating the admin to build into the proper folder.

**Comment by Gottwik** [comment]
Hey @justindra good job on the decoupling, I like it. Some test is failing, would you mind checking it out? Let me know if you have issues, I'll help.

**Comment by justindra** [comment]
Hi @Gottwik, yea it seems like the build failed as it is pulling the admin from npm and that version wasn't built with this PR. So not sure how you want to go about this?

**Comment by Gottwik** [comment]
oh, yea I get it, I can get that done.

Just to double check, are you happy with the **build** name?

I like the idea of putting underscore in front of the folder name to signify people should not edit the stuff. I also like **generated** because these files are actually generated ;-)

What do you think? I'll let you decide, just let me know to go ahead(we will have to change a bit of documentation as well).

**Comment by justindra** [comment]
I'm used to things using the `build` or `dist` names. But I don't mind whatever you'd like to use.

Also I just had an idea for backwards compatibility of the `_src` folder in case people are using they're own version of the admin and haven't updated that using the latest build. So I'll update that sometime today or tomorrow, and you can re-check things.

**Comment by Gottwik** [comment]
Wow, good job! Would you mind renaming it to '_generated' or '_static'? If you like 'build', I'll just go ahead and merge it as is.

**Comment by Gottwik** [comment]
Hey, tiny thing, could you please, please remove semicolons? There is also a eslintrc file to show the validation. I use this https://github.com/roadhump/SublimeLinter-eslint to show me the errors.

image

**Comment by justindra** [comment]
doneskies

**Comment by Gottwik** [comment]
I really appreciate your work. I've added you as a collaborator in case you would like to improve some other things. Let me know if you need any other resources(enduro's website admin login for example)?

**Comment by justindra** [comment]
Cool thanks! I have had some thoughts on what to add. I'll raise it in an issue and get your opinion on it.

**Pull request merged**
